language: cpp

sudo: false

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

matrix:
  exclude:
     - os: osx
       compiler: gcc

before_install:
 - curl --silent https://raw.githubusercontent.com/mapbox/mason/master/scripts/setup_cpp11_toolchain.sh -o ./cpp11 && source ./cpp11

install:
 - make

script:
 - make test

