language: cpp

sudo: false

compiler:
 - clang
 - gcc

before_install:
 - curl https://raw.githubusercontent.com/mapbox/mason/master/scripts/setup_cpp11_toolchain.sh -o ./cpp11 && source ./cpp11
install:
 - make

script:
 - make test